ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
    cert-manager.io/cluster-issuer: "letsencrypt-cloudflare"
    external-dns.alpha.kubernetes.io/target: "8.44.158.127"
  hosts:
    - host: audiobookshelf.nickknows.net
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: audiobookshelf-tls
      hosts:
        - audiobookshelf.nickknows.net

audiobookshelf:
  config:
    persistence:
      enabled: true
      storageClassName: rook-ceph-block
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
  metadata:
    persistence:
      enabled: true
      storageClassName: rook-ceph-block
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
  library:
    persistence:
      enabled: true
      storageClassName: rook-ceph-block
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Gi
  backup:
    persistence:
      enabled: true
      storageClassName: rook-ceph-block
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi