ingress:
  enabled: true
  annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "false"
      cert-manager.io/cluster-issuer: "letsencrypt-cloudflare"
      kubernetes.io/ingress-class: nginx
      external-dns.alpha.kubernetes.io/target: "8.44.158.127"
  class: nginx
  host: code.nickknows.net
  tls: true