spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/Gin-G/argo-k8s-stuff
    targetRevision: main
"nick-knows":
  enable: true
  source:
    repoURL: https://github.com/Gin-G/NickKnows
"nfl-api":
  enable: true
  source:
    repoURL: https://github.com/Gin-G/NFL-API
    targetRevision: main
codeserver:
  enable: false
  source:
    repoURL:  https://github.com/coder/code-server.git
    targetRevision: main
defs:
  enable: true
  source:
    repoURL:  git@github.com:Gin-G/DeFS.git
    targetRevision: main
defs-dev:
  enable: false
  source:
    repoURL:  git@github.com:Gin-G/DeFS.git
    targetRevision: main
defs-svelte:
  enable: true
  source:
    repoURL:  git@github.com:Gin-G/DeFS.git
    targetRevision: main
skitunes:
  enable: true
  source:
    repoURL: https://github.com/Gin-G/SkiTunes
    targetRevision: main
whokan:
  enable: true
  source:
    repoURL: https://github.com/Gin-G/Whookan
    targetRevision: main
rts:
  enable: true
  source:
    repoURL: git@github.com:Gin-G/ratetheslopes
    targetRevision: main
skitunes-dev:
  enable: false
  source:
    repoURL: https://github.com/Gin-G/SkiTunes
    targetRevision: db-switch
dbtest:
  enable: true
  source:
    repoURL: https://github.com/Gin-G/db-notes
    targetRevision: main