apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
data:
  services.yaml: |
    ---
    - Infratructure:
        - Argo CD:
            href: https://argocd.nickknows.net
            description: GitOps Continuous Delivery
            icon: argocd.png
            widget:
              type: argocd
              url: https://argocd.nickknows.net
              key: YOUR_ARGOCD_TOKEN
    - Media:
        - Plex:
            href: http://192.168.4.45:32400/web
            description: Media Server
            icon: plex.png
            widget:
              type: plex
              url: http://192.168.4.45:32400
              key: {{HOMEPAGE_VAR_PLEX_TOKEN}}
        - Audiobookshelf:
            href: https://audiobookshelf.nickknows.net
            description: Audio Book Server
            icon: audiobookshelf.png
            widget:
              type: audiobookshelf
              url: https://audiobookshelf.nickknows.net
              key: YOUR_PLEX_TOKEN
          
  kubernetes.yaml: |
    mode: cluster
    
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          label: "Cluster Overview"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true