spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/Gin-G/argo-k8s-stuff
    targetRevision: main
"argo-cd":
  enable: true
  targetRevision: 9.3.7
"argo-rollouts":
  enable: true
  targetRevision: 2.40.5
"cert-manager":
  enable: true
  targetRevision: 1.19.2
cnpg:
  enable: true
  targetRevision: 0.27.0
"external-secrets":
  enable: true
  targetRevision: 1.3.1
externaldns:
  enable: true
  targetRevision: 1.20.0
homepage:
  enable: true
  targetRevision: 1.8.0
lgtm:
  enable: true
  targetRevision: 3.0.1
nginx:
  enable: true
  targetRevision: 4.14.2
openbao:
  enable: true
  targetRevision: 0.23.5
prometheus:
  enable: true
  targetRevision: 81.3.1
promtail:
  targetRevision: 6.16.6
rook-ceph:
  enable: true
  targetRevision: v1.19.0
"argo-workflows":
  enable: false
  targetRevision: 0.42.5
backstage:
  enable: false
  targetRevision: 2.2.0
buildkit:
  enable: false
  targetRevision: 0.8.0
harbor:
  enable: false
  targetRevision: 1.16.0
nvidia:
  enable: false
  targetRevision: 0.17.0
  operatorRevision: v24.9.2
rancher:
  enable: false